### ISSUE TITLE
Не совсем корректная работа с валютами

### ISSUE THREAD

**Issue by frommax** [begateway/cs-cart-payment-module#4]
Здравствуйте! Смотрите, суть проблемы такая. 

Вот есть белорусский магазин с одной валютой BYN, она базовая и других валют нет. Модуль работает корректно, оплаты все проходят. 

Некоторая часть покупателей нашего магазина из России. Но к большому сожалению наши соседи не всегда отличают белорусский рубль от российского. Было принято решение добавить вторую валюту на сайт - это российский рубль, далее определять местоположение покупателя и если он из России, то показывать ему цены сразу в российских рублях. Но если мы меняем валюту на сайте на российский рубль, то и в корзине будет российский рубль. Мы выбираем оплату Онлайн через bePaid  и при таком раскладе на платёжный шлюз передается сумма в российских рублях, а мы не можем принимать оплату в российских рублях. 

Как бы поправить модуль так, чтобы не зависимо какая валюта выбрана на сайте в модуль оплаты залетала базовая валюта BYN?

**Comment by avsh** [comment]
Здравствуйте! 

Исходя из описания, я понимаю, что ваше решение самостоятельно не приводит валюту на сайте (RUB) к базовой валюте cs-cart (BYN). Ваша проблема может быть решена несколькими вариантами.

Вариант 1

На стороне сервиса может быть включен конвертер перевода RUB->BYN по справочным курсам и в систему на оплату пойдет cумма в BYN

Вариант 2

Обратиться к вашему аккаунт-менеджеру, чтобы влючили поддержку платежей в RUB для карт Мир. Вам будет зачислена выручка в BYN по курсу НСПК.

Вариант 3

Разобраться с настройками валют в cs-cart, чтобы на оплату приходила сумма в BYN, согласно заданным курсам.

**Comment by frommax** [comment]
В CS-Cart 2 валюты:
1) BYN (базовая)
2) RUB 

Можно через переключатель валют их переключать, курс в админке задается. Впрочем как и во всех интернет-магазинах.

Если выбрана валюта BYN, сумма в платежный шлюз передается в BYN и все платежи проходят.
Если на сайте выбрана валюта RUB, сумма в платежный шлюз передается в RUB и при переходе на страницу оплаты пишет что-то вроде "ошибка, для вас нет доступных способов оплаты", если нажимаем "Закрыть" то возвращаемся на сайт и получаем ошибку "Sorry, service is temporarily unavailable."

Насколько я понимаю "Вариант 2" решения, тот что Вы предложили подходит. Или нужно как-то чтоб при выбранной валюте RUB на платежный шлюз все равно передавалось в базовой валюте BYN.

**Comment by frommax** [comment]
Аккаунт менеджер говорит, что:

Вариант 1 - это не выгодно, т.к. там конвертация может быть 4 раза с одной валюты в другую, пока не получится BYN.
Вариант 2 - банки не проводят платежи по картам МИР в RUB

Поэтому вопрос, как поправить модуль так, чтобы не зависимо какая валюта RUB или USD выбрана на сайте, она являлась справочной, а на платежный шлюз всегда передавалась стоимость в BYN (базовая валюта)?

Например на сайте BYN (базовая, именно в этой валюте все цены заданы) и RUB (справочная), я выбрал валюту RUB добавил товар в корзину, у меня стоимость товара и итоговая сумма в корзине в RUB. Я выбираю оплату через bePaid, нажимаю оформить заказ, на платежный шлюз идет цена в BYN.

**Comment by avsh** [comment]
В версии [1.6.0](https://github.com/begateway/cs-cart-payment-module/releases/download/1.6.0/cs-cart-payment-module.zip) добавлена настройка валюты в метод оплаты

- если в настройках выбрана валюта, то она будет использована для оплаты
- если валюта не выбрана, то на оплату отсылается валюта пользователя

**Comment by frommax** [comment]
Спасибо большое! Проверил, вроде все отлично работает.
